### PR TITLE
Improve memory efficiency of the client

### PR DESCRIPTION
**Pull request by PaulusParssinen**
In this PR I had an attempt to reduce GC pressure a bit by removing unnecessary memory allocations.

### Commits
* d4d385f Avoid allocating `JsonSerializerOptions` for every `NostrEventTag.ToString()` call
* 68b5a81 Use BCL `Convert.[To/From]HexString()` instead of manual loop. 
  * This one is SIMD accelerated in the BCL. 
* 933831c Improve efficiency of the ``NostrClient`` IO event loop.
  * Because `Channel<string>` are private and we control the readers/writer, we can hint it with options to allow some nice optimizations behind the scenes. The ``_pendingOutgoingMessages`` channel can have multiple concurrent writers however! But still one reader loop.
  * Remember to dispose ``CancellationTokenSource``s
  * Few ``ConfigureAwait(false)`` which are pratically the default for .NET libraries. Didn't go through everything so there's still more places for it.
  * Use ``ValueTask<ValueWebSocketReceiveResult> ClientWebSocket.ReadAsync(Memory<byte> buffer, ..)`` overload to avoid allocations in the main IO loop.
* c0db021 Optimize BIP340 signing a bit more
  * ``stackalloc`` all the way 🚀 
* fd23bd0 Optimize NIP-04 to use crypto one-shot functions instead of streams.
  * These are recent additions to `S.Security.Cryptography` namespace and simplify code a lot in addition to performance.
  * I noticed this reverts your change in 7bede830e2e45f5ed5ec6dc266bb5ccf6037f858, however I'd like to argue that there is nothing asynchronous about AES encryption which only adds extra overhead. I'm also interested where one would like to swap out the BCL provided AES implementation. I'm open to adding the AES swapping back though, I just think the AES implementation could be swapped by giving the `NIP04` methods instance of the implemented custom [``Aes``](https://github.com/dotnet/runtime/blob/b69fa275565ceeca8ba39f7f9bcb1e301dd68ded/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/Aes.cs#L10) class.
* Commits include some attempt to have consistent naming & follow standard .NET API  library conventions. These are subjective so I'm open to revert those if need to be.

### CODE REVIEW

**Comment by Kukks** [comment]
Wow this is great, thanks for doing this! Will review tomorrow

**Comment by kfrancis** [comment]
Once you do, I'll take a swing at the tests as well

**Comment by PaulusParssinen** [comment]
Test coverage in this project is to poor to say the least. The existing couple unit tests covers the `NIP04` but not much else.

**Comment by kfrancis** [comment]
@PaulusParssinen Yea, I had quite a few in my repo that mainly used NNostr bits (but at the time I wasn't sure if this lib was going to be maintained): https://github.com/kfrancis/NuSocial/tree/main/tests/NostrLib.Tests that I'll bring over

**Review by Kukks — CHANGES_REQUESTED** [review]
So the main reason i had abstracted the aes into a separate class with interface was that it was not supported when compiling to wasm and had to roll out some browser bridging logic (which resulted in the async)  See: https://github.com/Kukks/Salr/blob/master/Salr.WASM/WasmAES.razor

Maybe net7 supports AES natively now but haven't checked.

**Comment by PaulusParssinen** [comment]
There _was_ plan to add `AES-256-CBC` support using SubtleCrypto to .NET 7 but was scrapped due to issues with the `SharedArrayBuffer` (Entire mess is documented here https://github.com/dotnet/runtime/issues/40074). Forgot that the JS interop required doing sync-over-async.. pain. 

Added an new minimal `IAesEncryption` interface which should suit WASM scenarios requirements. Does the new optional parameter work for you or did you like the static property more?

Can't also help but notice the fact that NIP-04 specification itself is harmful. Lacks authentication and fails catastrophically if either sides keys leak.

**Comment by Kukks** [comment]
> There _was_ plan to add `AES-256-CBC` support using SubtleCrypto to .NET 7 but was scrapped due to issues with the `SharedArrayBuffer` (Entire mess is documented here [dotnet/runtime#40074](https://github.com/dotnet/runtime/issues/40074)). Forgot that the JS interop required doing sync-over-async.. pain.
> 
> Added an new minimal `IAesEncryption` interface which should suit WASM scenarios requirements. Does the new optional parameter work for you or did you like the static property more?
> 
> Can't also help but notice the fact that NIP-04 specification itself is harmful. Lacks authentication and fails catastrophically if either sides keys leak.

Check out this wrteup by @lontivero on an upgraded approach for NIP4 
nostr priv keys

**Review by Kukks — APPROVED** [review]

**Pull request merged**
